'''
Description: Model-to-Model (M2M) Transformation Engine. Parses natural language to PIM (JSON) via LLMs.
Author: Zhao zeyu
Date: 2026-02-28 03:18:40
LastEditors: Zhao zeyu
LastEditTime: 2026-03-01 04:05:11
FilePath: /MAFIS-Gen/pipeline/m2m_transformer.py
'''

import os
import json
from llm_prompts import SYSTEM_PROMPT, get_user_prompt

# To enable automated API calls, please uncomment the following and install the corresponding SDK (such as openai).
# from openai import OpenAI

def transform_nl_to_pim(nl_file_path, schema_file_path, output_pim_path):
    print(f"🔄 [M2M] Starting transformation from Natural Language to PIM...")
    
    # 1. Read input domain text and M2 metamodel schema
    with open(nl_file_path, 'r', encoding='utf-8') as f:
        nl_input = f.read()
    with open(schema_file_path, 'r', encoding='utf-8') as f:
        schema_content = f.read()

    # 2. Construct the LLM Prompt
    user_prompt = get_user_prompt(nl_input, schema_content)
    
    # ---------------------------------------------------------
    # 3. LLM API Invocation 
    # ---------------------------------------------------------
    print(" [M2M] Sending constraints and domain logic to the LLM engine...")
    
    """
    [API INTEGRATION GUIDE]
    This framework is Model-Agnostic. You can easily integrate any LLM that supports JSON mode 
    (e.g., GPT-4, DeepSeek-Coder, Gemini, Claude) by uncommenting and configuring the code below.
    
    Example using standard OpenAI API format (Compatible with DeepSeek, etc., by changing base_url):
    
    client = OpenAI(
        api_key="YOUR_API_KEY",
        # base_url="https://api.deepseek.com/v1" # Uncomment for DeepSeek or other compatible APIs
    )
    
    response = client.chat.completions.create(
        model="gpt-4-turbo", # or "deepseek-chat", etc.
        response_format={ "type": "json_object" },
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt}
        ]
    )
    pim_content = response.choices[0].message.content
    pim_json = json.loads(pim_content)
    """

    # ---------------------------------------------------------
    # [OUT-OF-THE-BOX REPRODUCIBILITY MODE]
    # For peer review and open-source evaluation, we provide a pre-generated PIM JSON below.
    # This JSON was directly generated by the ChatGPT web interface using the exact prompts above.
    # It allows researchers to execute the entire MDE pipeline without configuring API keys or incurring token costs.
    # ---------------------------------------------------------
    pim_json = {
        "system_name": "AirportRevenueFIS",
        "inference_type": "Mamdani",           
        "defuzzification_method": "Centroid",   
        "input_variables": [
            {"name": "Satisfaction", "range": [1.0, 5.0, 0.1], "terms": [
                {"term_name": "Low", "mf_type": "gaussmf", "parameters": [1.5, 0.5]},
                {"term_name": "Medium", "mf_type": "gaussmf", "parameters": [3.0, 0.5]},
                {"term_name": "High", "mf_type": "gaussmf", "parameters": [4.5, 0.3]}
            ]},
            {"name": "Waiting_Time", "range": [0.0, 5.0, 0.1], "terms": [
                {"term_name": "Low", "mf_type": "trimf", "parameters": [0, 0, 1.8]},
                {"term_name": "Medium", "mf_type": "trimf", "parameters": [1.2, 2.25, 3.3]},
                {"term_name": "High", "mf_type": "trimf", "parameters": [2.7, 4.0, 5.0]}
            ]}
        ],
        "output_variables": [
            {"name": "Consumption", "range": [0, 90, 1], "terms": [
                {"term_name": "Little", "mf_type": "trimf", "parameters": [0, 0, 30]},
                {"term_name": "Average", "mf_type": "trimf", "parameters": [30, 45, 60]},
                {"term_name": "Great", "mf_type": "trimf", "parameters": [60, 90, 90]}
            ]}
        ],
        "rules": [
            {"rule_id": "R1", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "Low", "Waiting_Time": "Low"}, "consequent": {"Consumption": "Little"}},
            {"rule_id": "R2", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "Low", "Waiting_Time": "Medium"}, "consequent": {"Consumption": "Little"}},
            {"rule_id": "R3", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "Low", "Waiting_Time": "High"}, "consequent": {"Consumption": "Average"}},
            {"rule_id": "R4", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "Medium", "Waiting_Time": "Low"}, "consequent": {"Consumption": "Little"}},
            {"rule_id": "R5", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "Medium", "Waiting_Time": "Medium"}, "consequent": {"Consumption": "Average"}},
            {"rule_id": "R6", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "Medium", "Waiting_Time": "High"}, "consequent": {"Consumption": "Average"}},
            {"rule_id": "R7", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "High", "Waiting_Time": "Low"}, "consequent": {"Consumption": "Average"}},
            {"rule_id": "R8", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "High", "Waiting_Time": "Medium"}, "consequent": {"Consumption": "Great"}},
            {"rule_id": "R9", "weight": 1.0, "connection_type": "AND", "antecedents": {"Satisfaction": "High", "Waiting_Time": "High"}, "consequent": {"Consumption": "Great"}}
        ]
    }

    # 4. Save to PIM (JSON file)
    os.makedirs(os.path.dirname(output_pim_path), exist_ok=True)
    with open(output_pim_path, 'w', encoding='utf-8') as f:
        json.dump(pim_json, f, indent=4)
    
    print(f"✅ [M2M] Successfully generated PIM model to: {output_pim_path}")
    return output_pim_path

if __name__ == "__main__":
    # Execute M2M test
    transform_nl_to_pim(
        nl_file_path="../inputs/airport_revenue_scenario.txt",
        schema_file_path="../metamodels/fis_schema.json",
        output_pim_path="../generated_outputs/pim.json"
    )